# Generated by Django 5.0.3 on 2024-03-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_spicy', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
